version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: triguard_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
    networks:
      - triguard_network

networks:
  triguard_network:
    driver: bridge