"""Customers and Users are required to provide location details object

Revision ID: 5b8fd433d9d1
Revises: 652e0fcfc298
Create Date: 2025-10-29 04:00:48.923782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b8fd433d9d1'
down_revision = '652e0fcfc298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.drop_column('address')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
