"""Added email to user as required field

Revision ID: 652e0fcfc298
Revises: bdfd93652334
Create Date: 2025-10-28 23:22:08.348143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652e0fcfc298'
down_revision = 'bdfd93652334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
