"""Initial schema

Revision ID: 66c2a664e61c
Revises: 
Create Date: 2025-10-27 20:07:21.333673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c2a664e61c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('roles_permissions_id_fkey'), type_='foreignkey')
        batch_op.drop_column('permissions_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('roles_permissions_id_fkey'), 'permissions', ['permissions_id'], ['code'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
