"""Convert to many-to-many role-permission relationship

Revision ID: 69ddbd415e53
Revises: 66c2a664e61c
Create Date: 2025-10-27 20:16:32.858929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ddbd415e53'
down_revision = '66c2a664e61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permissions.code'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_code')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('permissions_role_id_fkey'), type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('permissions_role_id_fkey'), 'roles', ['role_id'], ['id'])

    op.drop_table('role_permissions')
    # ### end Alembic commands ###
